-- Run in the Supabase SQL editor (Dashboard → SQL Editor). Safe to re-run.

-- --- Icon vocabulary --------------------------------------------------------
-- The vocabulary the LLM may choose from. Keys must match the ICONS map in lib/sectionIcons.tsx.
create table if not exists public.icons (
  key text primary key
);

-- The old name → icon cache is gone: icons now live on sections.icon.
drop table if exists public.section_icons;

-- --- Templates --------------------------------------------------------------
-- templates 1─* sections 1─* subsections 1─* comments. Ids are generated by the database;
-- the editor's temporary client ids are mapped to real ones by save_template().
create table if not exists public.templates (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  -- False until the LLM has been asked for section icons (see apply_section_icons).
  icons_resolved  boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create unique index if not exists templates_name_key on public.templates (lower(name));

create table if not exists public.sections (
  id           uuid primary key default gen_random_uuid(),
  template_id  uuid not null references public.templates (id) on delete cascade,
  name         text not null,
  icon         text references public.icons (key),
  hidden       boolean not null default false,
  position     int  not null
);
create index if not exists sections_template_idx on public.sections (template_id, position);

create table if not exists public.subsections (
  id          uuid primary key default gen_random_uuid(),
  section_id  uuid not null references public.sections (id) on delete cascade,
  name        text not null,
  hidden      boolean not null default false,
  position    int  not null
);
create index if not exists subsections_section_idx on public.subsections (section_id, position);

create table if not exists public.comments (
  id             uuid primary key default gen_random_uuid(),
  subsection_id  uuid not null references public.subsections (id) on delete cascade,
  name           text not null default '',
  text           text not null default '',     -- rich-text HTML from tiptap
  type           text not null check (type in ('defect', 'info', 'limit')),
  category       text not null default '' check (category in ('', '-1', '0', '1')),
  options        text not null default '',     -- comma-separated multiple-choice options
  answer_type    text not null default 'boolean',
  extra          jsonb not null default '{}', -- unmapped spreadsheet columns, for round-trip export
  hidden         boolean not null default false,
  position       int  not null
);
create index if not exists comments_subsection_idx on public.comments (subsection_id, position);

-- Added after the first version: "hidden" items are dimmed in the editor and left out of the PDF export.
alter table public.sections    add column if not exists hidden boolean not null default false;
alter table public.subsections add column if not exists hidden boolean not null default false;
alter table public.comments    add column if not exists hidden boolean not null default false;

-- The list page's rows, with counts (the app builds "3 sections · …" from these).
create or replace view public.template_list with (security_invoker = true) as
select
  t.id, t.name, t.created_at, t.updated_at,
  (select count(*) from public.sections s where s.template_id = t.id) as sections,
  (select count(*) from public.subsections ss join public.sections s on s.id = ss.section_id
     where s.template_id = t.id) as subsections,
  (select count(*) from public.comments c
     join public.subsections ss on ss.id = c.subsection_id
     join public.sections s on s.id = ss.section_id
     where s.template_id = t.id) as comments
from public.templates t;

-- --- Access -----------------------------------------------------------------
-- No auth yet: the app uses the publishable (anon) key, so these policies let anyone do anything.
-- Tighten (owner_id + auth.uid()) before this holds anything private.
do $$
declare t text;
begin
  foreach t in array array['icons', 'templates', 'sections', 'subsections', 'comments'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "open access" on public.%I', t);
  end loop;
  -- Icons stay read-only.
  drop policy if exists "icons are readable" on public.icons;
  create policy "open access" on public.icons for select using (true);
  foreach t in array array['templates', 'sections', 'subsections', 'comments'] loop
    execute format('create policy "open access" on public.%I for all using (true) with check (true)', t);
  end loop;
end $$;

-- --- Functions --------------------------------------------------------------
create or replace function public.uuid_or_null(p text) returns uuid
language plpgsql immutable as $$
begin
  return p::uuid;
exception when invalid_text_representation then
  return null;
end $$;

-- Writes a whole tree ([{ id, name, icon, subsections: [{ id, name, comments: [...] }] }]) in one
-- transaction. Rows are matched by id *within this template only*; anything unmatched (including
-- ids that belong to another template) is inserted with a fresh database id. Rows missing from
-- the tree are deleted. Returns { <client id>: <new database id> } for every inserted row so the
-- editor can swap its temporary ids.
create or replace function public.save_template(p_id uuid, p_name text, p_tree jsonb)
returns jsonb language plpgsql as $$
declare
  v_map jsonb := '{}';
  v_sec_ids uuid[] := '{}';
  v_sub_ids uuid[] := '{}';
  v_com_ids uuid[] := '{}';
  s jsonb; sub jsonb; c jsonb;
  s_pos int; sub_pos int; c_pos int;
  v_cid text; v_sid uuid; v_subid uuid; v_comid uuid; v_icon text;
begin
  perform 1 from public.templates where id = p_id for update; -- serialise concurrent saves
  if not found then raise exception 'Template not found' using errcode = 'P0002'; end if;

  update public.templates
     set name = coalesce(nullif(btrim(p_name), ''), name), updated_at = now()
   where id = p_id;

  for s, s_pos in select e.value, (e.ordinality - 1)::int from jsonb_array_elements(p_tree) with ordinality e loop
    v_cid := s->>'id';
    v_icon := (select key from public.icons where key = s->>'icon');
    select id into v_sid from public.sections
     where id = public.uuid_or_null(v_cid) and template_id = p_id;
    if v_sid is null then
      insert into public.sections (template_id, name, icon, hidden, position)
      values (p_id, coalesce(s->>'name', ''), v_icon, coalesce(s->'hidden' = 'true'::jsonb, false), s_pos)
      returning id into v_sid;
      if v_cid is not null then v_map := v_map || jsonb_build_object(v_cid, v_sid); end if;
    else
      update public.sections
         set name = coalesce(s->>'name', ''), icon = v_icon, hidden = coalesce(s->'hidden' = 'true'::jsonb, false),
             position = s_pos
       where id = v_sid;
    end if;
    v_sec_ids := v_sec_ids || v_sid;

    for sub, sub_pos in select e.value, (e.ordinality - 1)::int
                          from jsonb_array_elements(coalesce(s->'subsections', '[]')) with ordinality e loop
      v_cid := sub->>'id';
      select ss.id into v_subid from public.subsections ss
        join public.sections sc on sc.id = ss.section_id
       where ss.id = public.uuid_or_null(v_cid) and sc.template_id = p_id;
      if v_subid is null then
        insert into public.subsections (section_id, name, hidden, position)
        values (v_sid, coalesce(sub->>'name', ''), coalesce(sub->'hidden' = 'true'::jsonb, false), sub_pos)
        returning id into v_subid;
        if v_cid is not null then v_map := v_map || jsonb_build_object(v_cid, v_subid); end if;
      else
        update public.subsections
           set section_id = v_sid, name = coalesce(sub->>'name', ''),
               hidden = coalesce(sub->'hidden' = 'true'::jsonb, false), position = sub_pos
         where id = v_subid;
      end if;
      v_sub_ids := v_sub_ids || v_subid;

      for c, c_pos in select e.value, (e.ordinality - 1)::int
                        from jsonb_array_elements(coalesce(sub->'comments', '[]')) with ordinality e loop
        v_cid := c->>'id';
        select cm.id into v_comid from public.comments cm
          join public.subsections ss on ss.id = cm.subsection_id
          join public.sections sc on sc.id = ss.section_id
         where cm.id = public.uuid_or_null(v_cid) and sc.template_id = p_id;
        if v_comid is null then
          insert into public.comments
            (subsection_id, name, text, type, category, options, answer_type, extra, hidden, position)
          values (
            v_subid, coalesce(c->>'name', ''), coalesce(c->>'text', ''), coalesce(c->>'type', 'info'),
            coalesce(c->>'category', ''), coalesce(c->>'options', ''), coalesce(c->>'answerType', 'boolean'),
            case when jsonb_typeof(c->'extra') = 'object' then c->'extra' else '{}'::jsonb end,
            coalesce(c->'hidden' = 'true'::jsonb, false), c_pos
          ) returning id into v_comid;
          if v_cid is not null then v_map := v_map || jsonb_build_object(v_cid, v_comid); end if;
        else
          update public.comments set
            subsection_id = v_subid, name = coalesce(c->>'name', ''), text = coalesce(c->>'text', ''),
            type = coalesce(c->>'type', 'info'), category = coalesce(c->>'category', ''),
            options = coalesce(c->>'options', ''), answer_type = coalesce(c->>'answerType', 'boolean'),
            extra = case when jsonb_typeof(c->'extra') = 'object' then c->'extra' else '{}'::jsonb end,
            hidden = coalesce(c->'hidden' = 'true'::jsonb, false), position = c_pos
          where id = v_comid;
        end if;
        v_com_ids := v_com_ids || v_comid;
      end loop;
    end loop;
  end loop;

  -- Rows that were not in the tree. Moved rows were re-parented above, so they survive.
  delete from public.comments cm using public.subsections ss, public.sections sc
   where cm.subsection_id = ss.id and ss.section_id = sc.id and sc.template_id = p_id
     and cm.id <> all (v_com_ids);
  delete from public.subsections ss using public.sections sc
   where ss.section_id = sc.id and sc.template_id = p_id and ss.id <> all (v_sub_ids);
  delete from public.sections where template_id = p_id and id <> all (v_sec_ids);

  return v_map;
end $$;

-- Import: a new template with a unique name ("Report" → "Report 2"). Every id in the tree is
-- ignored and regenerated. Returns { id, name, createdAt }.
create or replace function public.create_template(p_name text, p_tree jsonb, p_icons_resolved boolean default false)
returns jsonb language plpgsql as $$
declare
  v_base text := btrim(p_name);
  v_name text := btrim(p_name);
  v_n int := 2;
  v_id uuid;
  v_created timestamptz;
begin
  while exists (select 1 from public.templates where lower(name) = lower(v_name)) loop
    v_name := v_base || ' ' || v_n;
    v_n := v_n + 1;
  end loop;
  insert into public.templates (name, icons_resolved) values (v_name, p_icons_resolved)
  returning id, created_at into v_id, v_created;
  -- A brand-new template owns no rows, so every node in the tree is inserted with a fresh id.
  perform public.save_template(v_id, v_name, p_tree);
  return jsonb_build_object('id', v_id, 'name', v_name, 'createdAt', v_created);
end $$;

-- Stores LLM-chosen icons ({ <section id>: <icon key> }) for sections that have none yet, and marks
-- the template as done so the LLM is not asked again (sections it answered "none" for stay blank).
create or replace function public.apply_section_icons(p_template_id uuid, p_icons jsonb)
returns void language sql as $$
  update public.sections s set icon = i.value
    from jsonb_each_text(p_icons) i
   where s.id = public.uuid_or_null(i.key) and s.template_id = p_template_id and s.icon is null
     and i.value in (select key from public.icons);
  update public.templates set icons_resolved = true where id = p_template_id;
$$;

insert into public.icons (key) values
  ('home'),
  ('exterior'),
  ('roof'),
  ('interior'),
  ('foundation'),
  ('structure'),
  ('basement'),
  ('attic'),
  ('heating'),
  ('cooling'),
  ('hvac'),
  ('ventilation'),
  ('plumbing'),
  ('water'),
  ('electrical'),
  ('outlet'),
  ('lighting'),
  ('door'),
  ('window'),
  ('stairs'),
  ('garage'),
  ('kitchen'),
  ('bathroom'),
  ('bedroom'),
  ('laundry'),
  ('appliance'),
  ('refrigerator'),
  ('fireplace'),
  ('fire_safety'),
  ('smoke_detector'),
  ('wall'),
  ('floor'),
  ('ceiling'),
  ('paint'),
  ('fence'),
  ('landscaping'),
  ('vegetation'),
  ('driveway'),
  ('drainage'),
  ('pool'),
  ('pest'),
  ('insulation'),
  ('sun'),
  ('repair'),
  ('tools'),
  ('ladder'),
  ('safety'),
  ('waste'),
  ('bathroom_fixture'),
  ('general_information'),
  ('building_code'),
  ('region'),
  ('roof_slope'),
  ('roof_coverings'),
  ('product_approval'),
  ('roof_deck_attachment'),
  ('roof_to_wall_attachment'),
  ('roof_geometry'),
  ('secondary_water_resistance'),
  ('opening_protection_chart'),
  ('opening_protection'),
  ('inspector_information'),
  ('inspector_certification'),
  ('homeowner'),
  ('additional_information')
on conflict (key) do nothing;

-- Make the API pick up the new tables immediately.
notify pgrst, 'reload schema';
