import type { SupabaseClient } from "@supabase/supabase-js";
import { formatCounts, type Comment, type Section } from "./template";

// Templates live in Supabase (see supabase/schema.sql). Ids are generated by the database;
// the tree is written through the create_template / save_template functions in one transaction.
export type Template = {
  id: string;
  name: string;
  content: string; // derived summary, e.g. "3 sections · 9 subsections · 40 comments"
  createdAt: string;
};

// The full document, including the section → subsection → comment tree.
export type TemplateDoc = Template & { tree: Section[]; iconsResolved: boolean };

export class StoreError extends Error {
  constructor(message: string, readonly status: number) {
    super(message);
  }
}

const isUuid = (s: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s);

// Postgres errors → HTTP-friendly ones.
function fail(error: { code?: string; message: string }): never {
  if (error.code === "23505") throw new StoreError("A template with that name already exists.", 409);
  if (error.code === "P0002") throw new StoreError("Not found.", 404);
  throw new StoreError(error.message, 500);
}

const byPosition = <T extends { position: number }>(a: T, b: T) => a.position - b.position;

// The list view never needs the (large) tree.
export async function listTemplates(db: SupabaseClient): Promise<Template[]> {
  const { data, error } = await db.from("template_list").select("*").order("created_at", { ascending: false });
  if (error) fail(error);
  return data.map((r) => ({
    id: r.id,
    name: r.name,
    content: formatCounts(r.sections, r.subsections, r.comments),
    createdAt: r.created_at,
  }));
}

type CommentRow = {
  id: string; name: string; text: string; type: Comment["type"]; category: Comment["category"];
  options: string; answer_type: string; extra: Record<string, string>; hidden: boolean; position: number;
};

export async function getTemplate(db: SupabaseClient, id: string): Promise<TemplateDoc | null> {
  if (!isUuid(id)) return null;
  const { data, error } = await db
    .from("templates")
    .select(
      "id, name, icons_resolved, created_at, " +
      "sections(id, name, icon, hidden, position, subsections(id, name, hidden, position, comments(*)))",
    )
    .eq("id", id)
    .maybeSingle();
  if (error) fail(error);
  if (!data) return null;

  const t = data as unknown as {
    id: string; name: string; icons_resolved: boolean; created_at: string;
    sections: {
      id: string; name: string; icon: string | null; hidden: boolean; position: number;
      subsections: { id: string; name: string; hidden: boolean; position: number; comments: CommentRow[] }[];
    }[];
  };
  const tree: Section[] = t.sections.sort(byPosition).map((s) => ({
    id: s.id,
    name: s.name,
    ...(s.icon && { icon: s.icon }),
    ...(s.hidden && { hidden: true }),
    subsections: s.subsections.sort(byPosition).map((sub) => ({
      id: sub.id,
      name: sub.name,
      ...(sub.hidden && { hidden: true }),
      comments: sub.comments.sort(byPosition).map((c) => ({
        id: c.id, name: c.name, text: c.text, type: c.type, category: c.category,
        options: c.options, answerType: c.answer_type, extra: c.extra,
        ...(c.hidden && { hidden: true }),
      })),
    })),
  }));

  let subsections = 0, comments = 0;
  for (const s of tree) {
    subsections += s.subsections.length;
    for (const sub of s.subsections) comments += sub.comments.length;
  }
  return {
    id: t.id,
    name: t.name,
    content: formatCounts(tree.length, subsections, comments),
    createdAt: t.created_at,
    iconsResolved: t.icons_resolved,
    tree,
  };
}

export async function addTemplate(
  db: SupabaseClient, name: string, tree: Section[], iconsResolved = false,
): Promise<Template> {
  const { data, error } = await db.rpc("create_template", {
    p_name: name, p_tree: tree, p_icons_resolved: iconsResolved,
  });
  if (error) fail(error);
  const t = data as { id: string; name: string; createdAt: string };
  const { data: row, error: listError } = await db.from("template_list").select("*").eq("id", t.id).single();
  if (listError) fail(listError);
  return { ...t, content: formatCounts(row.sections, row.subsections, row.comments) };
}

export async function removeTemplate(db: SupabaseClient, id: string): Promise<boolean> {
  if (!isUuid(id)) return false;
  const { data, error } = await db.from("templates").delete().eq("id", id).select("id");
  if (error) fail(error);
  return data.length > 0;
}

/** Renames and/or replaces the tree. Returns the id map for rows the database created (client id → real id). */
export async function updateTemplate(
  db: SupabaseClient, id: string, patch: { name?: string; tree?: Section[] },
): Promise<{ idMap: Record<string, string> } | null> {
  if (!isUuid(id)) return null;
  if (patch.tree) {
    const { data, error } = await db.rpc("save_template", { p_id: id, p_name: patch.name ?? "", p_tree: patch.tree });
    if (error) {
      if (error.code === "P0002") return null;
      fail(error);
    }
    return { idMap: data as Record<string, string> };
  }
  if (patch.name !== undefined) {
    const { data, error } = await db
      .from("templates")
      .update({ name: patch.name, updated_at: new Date().toISOString() })
      .eq("id", id)
      .select("id");
    if (error) fail(error);
    if (data.length === 0) return null;
  }
  return { idMap: {} };
}
